version: '3.8'
services:
  app:
    build: .
    container_name: fastapi_project
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - './app:/code/app'

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      - pg_db
  pg_db:
    image: postgres:15.0-alpine
    container_name: pg_db
    volumes:
      - ./pg_db/:/var/lib/postgresql/data/
    env_file:
      - .env



    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
