"""add company47

Revision ID: 528a2b52a5bc
Revises: f014491ab45a
Create Date: 2023-04-21 14:44:32.515933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528a2b52a5bc'
down_revision = 'f014491ab45a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('owner_email', sa.String(), nullable=True))
    op.create_foreign_key(None, 'invite', 'user', ['owner_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite', type_='foreignkey')
    op.drop_column('invite', 'owner_email')
    # ### end Alembic commands ###
