"""add company50

Revision ID: 5c4a5881a63a
Revises: db2282bf313a
Create Date: 2023-04-21 15:25:39.475396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4a5881a63a'
down_revision = 'db2282bf313a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('owner_email', sa.String(), nullable=True))
    op.create_foreign_key(None, 'invite', 'user', ['owner_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite', type_='foreignkey')
    op.drop_column('invite', 'owner_email')
    # ### end Alembic commands ###
