"""add company52

Revision ID: 6720559470ec
Revises: 8af5e1173353
Create Date: 2023-04-21 15:34:55.071955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6720559470ec'
down_revision = '8af5e1173353'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_keywords', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('company_keywords_owner_email_fkey', 'company_keywords', type_='foreignkey')
    op.create_foreign_key(None, 'company_keywords', 'user', ['user_id'], ['id'])
    op.drop_column('company_keywords', 'owner_email')
    op.drop_constraint('invite_owner_email_fkey', 'invite', type_='foreignkey')
    op.drop_column('invite', 'owner_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('owner_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('invite_owner_email_fkey', 'invite', 'user', ['owner_email'], ['email'])
    op.add_column('company_keywords', sa.Column('owner_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company_keywords', type_='foreignkey')
    op.create_foreign_key('company_keywords_owner_email_fkey', 'company_keywords', 'user', ['owner_email'], ['email'])
    op.drop_column('company_keywords', 'user_id')
    # ### end Alembic commands ###
