"""add company48

Revision ID: ae7dfc4aa396
Revises: 528a2b52a5bc
Create Date: 2023-04-21 14:49:54.532897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7dfc4aa396'
down_revision = '528a2b52a5bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invite_owner_email_fkey', 'invite', type_='foreignkey')
    op.drop_column('invite', 'owner_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('owner_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('invite_owner_email_fkey', 'invite', 'user', ['owner_email'], ['email'])
    # ### end Alembic commands ###
