"""add company55

Revision ID: ea91537110a7
Revises: 9c433a6aad36
Create Date: 2023-05-15 02:18:41.939292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea91537110a7'
down_revision = '9c433a6aad36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
