"""add company53

Revision ID: f36bd44c4f58
Revises: 6720559470ec
Create Date: 2023-05-14 23:14:35.143615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36bd44c4f58'
down_revision = '6720559470ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
